# This file was generated by GoReleaser. DO NOT EDIT.
cask "mitoriq-collector" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c0f55e8c9ce8401599818becadadcb2e383d9b7aad8d0c0a99c0b3a16593cd0d"
      url "https://github.com/mitoriq/collector/releases/download/v#{version}/mitoriq-collector_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e801fb4e850c2a1b3d17fc0bece6731a633e1ef8d1cb45e640d86816eae8909c"
      url "https://github.com/mitoriq/collector/releases/download/v#{version}/mitoriq-collector_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mitoriq-collector"
  desc "Metadata-only local collector for Mitoriq"
  homepage "https://github.com/mitoriq/collector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mitoriq-collector"

  # No zap stanza required

end
